# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
# use_frameworks!


pod ‘Masonry’
pod 'PNChart'
pod 'DCAnimationKit'
pod 'DCPathButton', '~> 2.1.3'